# Generated by Django 4.2.27 on 2026-03-02 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auditlog', '0009_alter_logentry_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='content type'),
        ),
    ]
